function [num,denom] = hs_z(b,a)
%
% usage: [num,denom] = hs_z(b,a)
%
% This function is to translate an H(s) to an H(z) 
% using the bilinear transformation.  
% Input:
%   numerator given by b (an M by 3 matrix),
%   denominator given by a (an N by 3 matrix).
%   These can be generated by the 
%   functions chby_hs and bw_hs.
% Output:
%   numerator given by num (an M by 3 matrix) and 
%   denominator given by denom (an N by 3 matrix).
%   These can be used with hzval to generate a 
%   frequency plot.
% 

[n,m]   = size(a);
[n1,m1] = size(b);

if m~=3|m1~=3,
  disp('These are not valid H(s) arrays.');
  return;
end;
if n~=n1,
  disp('The input numerator and denominator do not match up.');
  return;
end;

for k=1:n,
  denom(k,:) = [ (a(k,1)+a(k,2)+a(k,3)) -2*(a(k,1)-a(k,3)) ... 
                 (a(k,1)-a(k,2)+a(k,3)) ];
  num(k,:)   = [ (b(k,1)+b(k,2)+b(k,3)) -2*(b(k,1)-b(k,3)) ... 
                 (b(k,1)-b(k,2)+b(k,3)) ];
end;

return;
